#!/bin/sh
[ ! -n "$1" ] && echo "Usage: szet [query]" && return 1
[ ! -d $MAIN_REPOS_PATH/zet ] && echo "mainrepospath/zet not found" && return 1
query="$@"
filename=$(cd "$MAIN_REPOS_PATH"/zet && rg -H -i "$query" | head -1 | { read foo; echo ${foo%%:*}; });
[ -z ${filename## *} ] && echo "Nothing found for $query" && return 1
[ ${filename##*\.} != "md" ] && echo "Returned $filename, instead of a markdown file" && return 1
pandoc "$MAIN_REPOS_PATH"/zet/"$filename" | lynx --stdin
